
# Funcoes next:

# IMPORTS

import FuncaoNext as Skip_to
import Classes as Classes
import UserImputsAndGameOptions 
import InGameVisuals as InGameVisuals
import os

# Terminal Cleaner
def clear_terminal():
    os.system('cls' if os.name == 'nt' else 'clear')


# Dilema 1

def Dilema1():
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")
    print("|                                                                        ┏┓┏┓┏┓┏┓┓ ┓┏┏┓                                                                         |")
    print("|                                                                    -~- ┣ ┗┓┃ ┃┃┃ ┣┫┣┫ -~-                                                                     |")
    print("|                                                                        ┗┛┗┛┗┛┗┛┗┛┛┗┛┗                                                                         |")
    print("|                                                                                                                                                               |")
    print("|                                                    > [A] GRITAR POR AJUDA <      > [B] SEGUIR A SILHUETA DISCRETAMENTE <                                      |")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    while True:
        opcao = input("A sua escolha: ").strip()

        if opcao == 'A':
            print("|                                                                                                                                                               |")
            print("| Decides gritar por ajuda                                                                                                                                      |")
            print("| - " + (Classes.PlayerCharacter).Nome + " — " + "HEEEEEEEY! AJUDAAAAA!!                                                                                        ")
            Skip_to.NextDialogue()
            print("| A silhueta pára para te ouvir                                                                                                                                 |")
            Skip_to.NextDialogue()
            print("| - " + (Classes.PlayerCharacter).Nome + " — " + "HEY, ONDE ESTAMOS!? O QUE SE PASSA?!!                                                                         ")
            Skip_to.NextDialogue()
            print("| - Silhueta — Hi hihi hi hi hi hi hi hi hi hiiiiii...                                                                                                          |")
            Skip_to.NextDialogue()
            print("| A silhueta desaparece nos meandros da masmorra deixando ecos do seu riso ressoar pelos corredores.                                                            |")
            print("| Ela deixa-te na tua miséria apesar de lhe teres pedido ajuda.                                                                                                 |")
            Skip_to.NextDialogue()
            print("| - " +  (Classes.PlayerCharacter).Nome + " — " + "HEEEY! ONDE É QUE PENSAS QUE VAIS?!! SEU..                                                                     ")
            Skip_to.NextDialogue()
            print("| - ??? — ggGRRRHNAAAAAAAAAaarRRRRHhhhh!! (És interrompido por um grito desumano)                                                                               |")
            Skip_to.NextDialogue()
            Dilema1_A()
            break
           
        if opcao == 'B':
            print("|                                                                                                                                                               |")
            print("| Decides seguir a silhueta discretamente                                                                                                                       |")
            Skip_to.NextDialogue()
            print("| Fixas o teu olhar na silhueta para não a perder de vista e sais da tua cela pela porta danificada. Começas a seguir a silhueta.                               |")
            Skip_to.NextDialogue()
            print("| Durante vários minutos vagueias pelos corredores discretamente, a silhueta revela-se ser um bandido com um capaçete fabricado a partir de um velho balde      |")
            print("| de ferro.                                                                                                                                                     |")
            Skip_to.NextDialogue()
            print("| Este individuo desloca-se de forma inesperada, quase acrobática, colocando os pés em sítios muito específicos.                                                |")
            Skip_to.NextDialogue()
            print("| Ele parece conhecer os corredores de cor, por isso tentas copiar os seus movimentos...                                                                        |")
            Skip_to.NextDialogue()
            print("| *Crack.                                                                                                                                                       |")
            Skip_to.NextDialogue()
            print("| Pisas um velho osso que se desfaz com o teu peso, alertando o bandido.                                                                                        |")
            Skip_to.NextDialogue()
            print("| Ele percebe que estás a segui-lo e acelera o passo, até atingir uma alavanca na parede.                                                                       |")
            Skip_to.NextDialogue()
            print("| - Homem do Balde - *YIii HI HI HI HI HI  hi Hiiiiii....       *Clank!                                                                                         |")
            Skip_to.NextDialogue()
            print("| Ele vira-se para ti, dominado por risos sádicos, e ativa a alavanca enquanto te faz um sinal de adeus com a mão.                                              |")
            Skip_to.NextDialogue()
            print("| *Swooosh!                                                                                                                                                     |")
            Skip_to.NextDialogue()
            print("| O chão abre-se sob os teus pés e cais para dentro de uma armadilha de picos mortais embutidos numa cisterna de ácido.                                         |")
            Skip_to.NextDialogue()
            print("| Espetas-te em vários picos mas nenhum deles atinge orgãos vitais.                                                                                             |")
            Skip_to.NextDialogue()
            print("| Enquanto estás espetado e em agonia absoluta, os  teus pés e mãos mergulham ligeiramente no ácido que te rodeia e são corroídos lentamente.                   |")
            Skip_to.NextDialogue()
            print("| A ultima coisa que vês é o homem do balde a rir-te na cara enquanto ele te observa lá de cima.                                                                |")
            Skip_to.NextDialogue()
            print("| Homem do Balde - *YIii HI HI HI HI HI  hi HiiiiiiIIIII... HAAA HAHAAAA hAAAAAAA!!!                                                                            |")
            Skip_to.NextDialogue()
            print("| Morres num sofrimento além do imaginavel...                                                                                                                   |")
            Skip_to.NextDialogue()
            InGameVisuals.ASCII_YouDied()


            break
            
        else:
            print("ERRO: Escolha uma opcao válida.")


    if (Classes.PlayerCharacter).Barulho == True:
            print("| Ao levantar-te, o teu equipamento produz ruídos que alertam o que quer que seja a fonte daquele gritar.                                                       |")
            Dilema1_A()
    if (Classes.PlayerCharacter).Barulho == False:
            Dilema1_B()
 
# Caso tenhas sido barulhento 



def Dilema1_A():
    print("|                                                                                                                                                               |")
    print("| - ??? — gRRRHNAAAARrrg...  AAAgRRRHNAAAAaarRH!!! (Mais gritos)                                                                                                |")
    Skip_to.NextDialogue()
    print("| *DOUF, DOUF, DOUF... (Barulhos de Patas)                                                                                                                      |")
    Skip_to.NextDialogue()
    print("| Passos pesados ecoam pelos corredores na tua direção.                                                                                                         |")
    Skip_to.NextDialogue()
    print("| - ??? — ggGRRRHNAAAAAAAAAaarRH!!                                                                                                                              |")
    Skip_to.NextDialogue()
    print("| Ao gritares por ajuda alertaste a atenção de uma criatura!                                                                                                    |")
    Skip_to.NextDialogue()
    UserImputsAndGameOptions.ObservarArredores()
    InGameVisuals.ASCII_OLHO()
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                         | --------------------------------------------~- OBSERVAÇÕES -~------------------------------------------- |                          |")
    print("|                         |                                                                                                          |                          |")
    print("|                         | • A tua cela está cheia de restos humanos em putrefação.                                                 |                          |")
    print("|                         | • Não era uma poça de água, era uma poça de sangue na qual estavas deitado.                              |                          |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    Skip_to.NextDialogue()
    UserImputsAndGameOptions.ObservarArredores()
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                         | --------------------------------------------~- OBSERVAÇÕES -~------------------------------------------- |                          |")
    print("|                         |                                                                                                          |                          |")
    print("|                         | • As gotas a cair do teto, eram os restos pingantes de um soldado esventrado. Sem dúvida a mais recente  |                          |")
    print("|                         |   refeição da criatura que está neste momento a aproximar-se te ti...                                    |                          |")
    print("|                         | • Conclusão: Estás na tigela de comida de uma criatura sanguinária, e a sua próxima refeição és tu.      |                          |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                                                                                                                                                               |")
    Skip_to.NextDialogue()
    print("| A criatura está quase a chegar à tua cela. Toma uma decisão!                                                                                                  |")
    Skip_to.NextDialogue()
    Dilema1_A1()

# Foste barulhento e criatura está a ir ter contigo

def Dilema1_A1():
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")
    print("|                                                                        ┏┓┏┓┏┓┏┓┓ ┓┏┏┓                                                                         |")
    print("|                                                                    -~- ┣ ┗┓┃ ┃┃┃ ┣┫┣┫ -~-                                                                     |")
    print("|                                                                        ┗┛┗┛┗┛┗┛┗┛┛┗┛┗                                                                         |")
    print("|                                                                                                                                                               |")
    print("|                                   > [A] DISTRAIR A CRIATURA <                               > [B] FICAR NA CELA E NÃO FAZER NADA <                            |")
    print("|                                   > [C] TENTAR UM TUDO POR TUDO, CORRER! <                  > [D] OBSERVAR ARREDORES <                                        |")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")

    while True:
        opcao = input("A sua escolha: ")
        if opcao == 'X':
            import MainMenuAndCharCreation as Go_to_
            Go_to_.MainMenu()
            break
        if opcao == 'A':
            print("| Decides distrair a criatura                                                                                                                                   |")
            Skip_to.NextDialogue()
            print("| Pegas num braço meio podre que estava no chão e atiras para o corredor.                                                                                       |")
            Skip_to.NextDialogue()
            print("| A criatura reage como esperavas. O braço atrai a criatura, ela começa a come-lo raivozamente.                                                                 |")
            Skip_to.NextDialogue()
            print("| Ganhaste algum tempo com este pequeno truque. Aproveita o momento de distração da criatura.                                                                   |")
            Skip_to.NextDialogue()
            print("|                                                                                                                                                               |")
            print("|                                                                                                                                                               |")
            print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
            print("|                                                                                                                                                               |")
            print("|                                                                                                                                                               |")
            print("|                                                                        ┏┓┏┓┏┓┏┓┓ ┓┏┏┓                                                                         |")
            print("|                                                                    -~- ┣ ┗┓┃ ┃┃┃ ┣┫┣┫ -~-                                                                     |")
            print("|                                                                        ┗┛┗┛┗┛┗┛┗┛┛┗┛┗                                                                         |")
            print("|                                                                                                                                                               |")
            print("|                                   > [A] SAIR DA CELA FURTIVAMENTE <                         > [B] SAIR DA CELA A CORRER <                                     |")
            print("|                                   > [C] OBSERVAR ARREDORES <                                                                                                  |")
            print("|                                                                                                                                                               |")
            print("|                                                                                                                                                               |")
            print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
            print("|                                                                                                                                                               |")
            print("|                                                                                                                                                               |")
            
            while True:
                opcao = input("A sua escolha: ")
                if opcao == 'X':
                    import MainMenuAndCharCreation as Go_to_
                    Go_to_.MainMenu()
                if opcao == 'A':
                    print("|                                                                                                                                                               |")
                    print("| Tentas sair furtivamente da cela, pela porta que está danificada.                                                                                             |")
                    Skip_to.NextDialogue()
                    print("| Consegues sair em silêncio. Estàs mesmo atento à criatura, e constatas que ela não te viu.                                                                    |")
                    Skip_to.NextDialogue()
                    print("| *CRACK                                                                                                                                                        |")
                    Skip_to.NextDialogue()
                    print("| Esqueceste de olhar onde metias os pés... pizàste um osso e partiste-o ao meio, alertando a criatura.                                                         |")
                    Skip_to.NextDialogue()
                    print("| A criatura salta-te para cima e oblitera o teu pequeno corpo humano insignificante em alguns segundos.                                                        |")
                    Skip_to.NextDialogue()
                    InGameVisuals.ASCII_YouDied()
                if opcao == 'B':
                    print("| Decides sair da cela a correr                                                                                                                                 |")
                    Skip_to.NextDialogue()
                    print("| Sais da cela a correr o mais rápido possivel.                                                                                                                 |")
                    Skip_to.NextDialogue()
                    print("| A criatura vê-te e larga imediatamente o braço que tinha na boca. Ela salta-te para cima sem que possas reagir.                                               |")
                    Skip_to.NextDialogue()
                    print("| O impacto e a dor foram tão violentas que desmaias.                                                                                                           |")
                    Skip_to.NextDialogue()
                    print("| Enquanto estás inconsciente, és brutalmente devorado até ao ultimo pedaço...                                                                                  |")
                    Skip_to.NextDialogue()
                    print("| Pelo menos não tiveste de vivenciar a tua própria morte.                                                                                                      |")
                    Skip_to.NextDialogue()
                    InGameVisuals.ASCII_YouDied()
                if opcao == 'C':
                    print("| Aproveitas a disctração da criatura para observar os teus arredores                                                                                           |")
                    Skip_to.NextDialogue()
                    UserImputsAndGameOptions.ObservarArredores()
                    InGameVisuals.ASCII_OLHO()
                    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
                    print("|                         | --------------------------------------------~- OBSERVAÇÕES -~------------------------------------------- |                          |")
                    print("|                         |                                                                                                          |                          |")
                    print("|                         | • No fundo da tua cela há um velho armário de madeira.                                                   |                          |")
                    print("|                         | • O armário tem o aspeto de um roupeiro com duas portas ligeiramente entreabertas.                       |                          |")
                    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
                    print("|                                                                                                                                                               |")
                    Skip_to.NextDialogue()
                    print("|                                                                                                                                                               |")
                    print("| A criatura está mesmo perstes a terminar de devorar o braço. Ela não ficará distraida por muito mais tempo.                                                   |")
                    Skip_to.NextDialogue()
                    print("|                                                                                                                                                               |")
                    print("|                                                                                                                                                               |")
                    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
                    print("|                                                                                                                                                               |")
                    print("|                                                                                                                                                               |")
                    print("|                                                                        ┏┓┏┓┏┓┏┓┓ ┓┏┏┓                                                                         |")
                    print("|                                                                    -~- ┣ ┗┓┃ ┃┃┃ ┣┫┣┫ -~-                                                                     |")
                    print("|                                                                        ┗┛┗┛┗┛┗┛┗┛┛┗┛┗                                                                         |")
                    print("|                                                                                                                                                               |")
                    print("|                                   > [A] FUGIR PARA DENTRO DO ARMÁRIO <                 > [B] FICAR DE PÉ, ESTÁTICO E EM SILÊNCIO <                            |")
                    print("|                                   > [C] ENFRENTAR A CRIATURA <                                                                                                |")
                    print("|                                                                                                                                                               |")
                    print("|                                                                                                                                                               |")
                    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
                    print("|                                                                                                                                                               |")
                    print("|                                                                                                                                                               |")
                    
                    opcao = ("A sua escolha: ")
                    while True:
                        opcao = input("A sua escolha: ").strip()
                        if opcao == 'A':
                            print("|                                                                                                                                                               |")
                            print("| Decides fugir para dentro do armário da tua cela                                                                                                              |")
                            Skip_to.NextDialogue()
                            print("| Ao abrir a porta direita do armário, a porta cai de podre e provoca um estrondão de barulhos de madeira.                                                      |")
                            Skip_to.NextDialogue()
                            print("| A criatura ouve isto e larga o petisco imediatamente. Furiosa ela acelera em direção à tua cela.                                                              |")
                            Skip_to.NextDialogue()
                            print("| Numa mistura de desespero e instinto, a tua adrenalina faz-te saltar para dentro do armário.                                                                  |")
                            Skip_to.NextDialogue()
                            print("| Percutas o fundo de mandeira do armário, partindo-o e revelando uma passagem secreta.                                                                         |")
                            Skip_to.NextDialogue()
                            print("| A criatura está prestes a entrar na tua cela a alta velocidade.                                                                                               |")
                            Skip_to.NextDialogue()
                            print("| Guiado pela adrenalina, consegues rápidamente levantar-te e deparas-te com a passagem secreta.                                                                |")
                            Skip_to.NextDialogue()
                            print("| Um longo corredor escuro estende-se sobre o que parece ser kilometros.                                                                                        |")
                            Skip_to.NextDialogue()
                            print("| A criatura entra violentemente na tua cela, partindo a porta que voa em pedaços. Ela joga-se contra o armário e tenta apanhar-te.                             |")
                            Skip_to.NextDialogue()
                            print("| Ela quase te apanha esticando o seu braço mutante , mas estás salvo. Ela é demasiado grande para caber neste túnel constrangido, adaptado às dimenções        |")
                            print("| de um corpo humano.                                                                                                                                           |")
                            Skip_to.NextDialogue()
                            print("| Criatura - AAAAAGHHHAAAGRRRHNAAAAAAAAAaarRH!!                                                                                                                 |")
                            Skip_to.NextDialogue()
                            print("| A criatura está furiosíssima! Ela retira o braço do túnel e descarga o seu ódio e raiva destruido a mistura de restos humanos e objetos partidos da tua cela. |")
                            Skip_to.NextDialogue()
                            print("| Avanças pelo corredor afora durante o que te parece horas. Eventualmente, vês a luz do dia...                                                                 |")
                            Skip_to.NextDialogue()
                            InGameVisuals.ASCII_LVLI_SUCCESS()
                            break
                        if opcao == 'B':
                            print("| Decides ficar na tua cela, de pé, estático e em silêncio                                                                                                      |")
                            Skip_to.NextDialogue()
                            print("| - " + (Classes.PlayerCharacter).Nome + " — " + "Esta criatura sobrevive no escuro, ela é provavelmente cega! (*pensamento)                                    ")
                            Skip_to.NextDialogue()
                            print("| - " + (Classes.PlayerCharacter).Nome + " — " + "E impregnei-me do cheiro putrefacto dos restos humanos desta cela, ela não me distinguirá pelo cheiro (*pensamento)")
                            Skip_to.NextDialogue()
                            print("| - Criatura — AAAAAAARRRRRRGHRhr!! HAAAGRRRHNAAAAAAAAAaarRH!!                                                                                                  |")
                            Skip_to.NextDialogue()
                            print("| *Thunk! Whack!                                                                                                                                                |")
                            Skip_to.NextDialogue()
                            print("| A criatura parte a porta da cela e dá-te uma patada no abdomen.                                                                                               |")
                            Skip_to.NextDialogue()
                            print("| És projetado sobre uma pilha de restos humanos, da qual farás parte dentro de segundos.                                                                       |")
                            Skip_to.NextDialogue()
                            print("| - Criatura — AHHRRRaAAAAAGHHHAAAGRR! RHNAAAAAAAAAaarRH!!                                                                                                      |")
                            Skip_to.NextDialogue()
                            print("| Petrificado pela situação, não te consegues mais mecher.                                                                                                      |")
                            Skip_to.NextDialogue()
                            print("| A ultima coisa que vês antes de a criatura devorar a tua cabeça, é a sua cara. Com dezenas de olhos de aranha e mandibulas grotescas.                         |")
                            Skip_to.NextDialogue()
                            print("| A criatura não era cega...                                                                                                                                    |")
                            Skip_to.NextDialogue()
                            InGameVisuals.ASCII_YouDied()
                            break
                        if opcao == 'C':
                            print("| Decides enfrentar a criatura                                                                                                                                  |")
                            Skip_to.NextDialogue()
                            print("| Cruzas olhares com a criatura... Mas não te sentes intimidado!                                                                                                |")
                            Skip_to.NextDialogue()
                            print("| - Criatura — RRRRAAAAAAAAGHHHAAAGRRRHNAAAAAAAAAaarRH!!")
                            Skip_to.NextDialogue()
                            print("| Armas-te de coragem e prepáras-te para batalhar com este monstro demoníaco! Avanças-te em direção à criatura armado de força e bravura!                       |")
                            Skip_to.NextDialogue()
                            print("| - " + (Classes.PlayerCharacter).Nome + " — " + "AO ATAAAAAAAQUE!!")
                            Skip_to.NextDialogue()
                            InGameVisuals.ASCII_YouDied()
                            break
                        else:
                            if opcao != 'A' and opcao != 'B' and opcao != 'C' and opcao != 'X':
                                print("ERRO: Escolha uma opcao válida.")


                else:
                    if opcao != 'A' and opcao != 'B' and opcao != 'C' and opcao != 'D' and opcao != 'X':
                        print("ERRO: Escolha uma opcao válida.")


                    
        if opcao == 'B':
            print("| Decides ficar na cela e não fazer nada                                                                                                                        |")                                                                                                                                                                             
            Skip_to.NextDialogue()
            print("| Um rato esfomeado surge da penumbra e morde-te profundamente no torneselo. Gritas de dor, alertando ainda mais a criatura.                                    |")
            Skip_to.NextDialogue()
            print("| A criatura revela-se a ti destruindo brutalmente a porta da tua cela.                                                                                         |")
            Skip_to.NextDialogue()
            print("| A porta voa-te na cara e projeta-te contra a parede. Com o choque do impacto não consegues mais mecher.                                                       |")
            Skip_to.NextDialogue()
            print("| A criatura coloca um pé  sobre ti e esmaga o teu peito lentamente, e de uma unica dentada devora a tua cabeça...                                              |")
            Skip_to.NextDialogue()
            InGameVisuals.ASCII_YouDied()
        if opcao == 'C':
            print("| Decides tentar um tudo por tudo, CORRER!                                                                                                                      |")
            Skip_to.NextDialogue()
            print("| Consegues escapar-te da cela passando pelo defeito na porta e comessas a correr!                                                                              |")
            Skip_to.NextDialogue()
            print("| Criatura - AAAAAGHHHAAAGRRRHNAAAAAAAAAaarRH!!                                                                                                                 |")
            Skip_to.NextDialogue()
            print("| A criatura viu-te a sair e está a correr a trás de ti                                                                                                         |")
            Skip_to.NextDialogue()
            print("| Corres de todas as tuas forças mas a criatura é de outro mundo. Ela é superior a humanos em todos os aspetos, incluindo velocidade.                           |")
            Skip_to.NextDialogue()
            print("| Durante a corrida a criatura salta-te para cima e oblitera o teu pequeno e fragil corpo humano em alguns segundos...                                          |")
            Skip_to.NextDialogue()
            InGameVisuals.ASCII_YouDied()
        if opcao == 'D':
            print("| Decides observar os arredores                                                                                                                                 |")
            Skip_to.NextDialogue()
            UserImputsAndGameOptions.ObservarArredores()
            InGameVisuals.ASCII_OLHO()
            print("|                                                                                                                                                               |")
            print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
            print("|                         | --------------------------------------------~- OBSERVAÇÕES -~------------------------------------------- |                          |")
            print("|                         |                                                                                                          |                          |")
            print("|                         | • Num lampejo de lucidês, a adrenalina revela-te um velho armário de madeira no fundo da tua cela.       |                          |")
            print("|                         | • O armário tem o aspeto de um roupeiro com duas portas ligeiramente entreabertas.                       |                          |")
            print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
            print("|                                                                                                                                                               |")
            Skip_to.NextDialogue()
            print("|                                                                                                                                                               |")
            print("|                                                                                                                                                               |")
            print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
            print("|                                                                                                                                                               |")
            print("|                                                                                                                                                               |")
            print("|                                                                        ┏┓┏┓┏┓┏┓┓ ┓┏┏┓                                                                         |")
            print("|                                                                    -~- ┣ ┗┓┃ ┃┃┃ ┣┫┣┫ -~-                                                                     |")
            print("|                                                                        ┗┛┗┛┗┛┗┛┗┛┛┗┛┗                                                                         |")
            print("|                                                                                                                                                               |")
            print("|                                   > [A] FUGIR PARA DENTRO DO ARMÁRIO <                 > [B] FICAR NA CELA E NÃO FAZER NADA <                                 |")
            print("|                                   > [C] ENFRENTAR A CRIATURA <                                                                                                |")
            print("|                                                                                                                                                               |")
            print("|                                                                                                                                                               |")
            print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
            print("|                                                                                                                                                               |")
            print("|                                                                                                                                                               |")
            
            opcao = ("A sua escolha: ")
            while True:
                opcao = input("A sua escolha: ").strip()
                if opcao == 'A':                                                                                                                                                              
                    print("| Decides fugir para dentro do armário da tua cela                                                                                                              |")
                    Skip_to.NextDialogue()
                    print("| Ao abrir a porta direita do armário, a porta cai de podre e provoca um estrondão de barulhos de madeira.                                                      |")
                    Skip_to.NextDialogue()
                    print("| A criatura ouve isto e, furiosa, acelera em direção à tua cela.                                                                                               |")
                    Skip_to.NextDialogue()
                    print("| Numa mistura de desespero e instinto, a tua adrenalina faz-te saltar para dentro do armário.                                                                  |")
                    Skip_to.NextDialogue()
                    print("| Percutas o fundo de mandeira do armário, partindo-o e revelando uma passagem secreta.                                                                         |")
                    Skip_to.NextDialogue()
                    print("| A criatura está prestes a entrar na tua cela a alta velocidade.                                                                                               |")
                    Skip_to.NextDialogue()
                    print("| Guiado pela adrenalina, consegues rápidamente levantar-te e deparas-te com a passagem secreta.                                                                |")
                    Skip_to.NextDialogue()
                    print("| Um longo corredor escuro estende-se sobre o que parece ser kilometros.                                                                                        |")
                    Skip_to.NextDialogue()
                    print("| A criatura entra violentemente na tua cela, partindo a porta que voa em pedaços. Ela joga-se contra o armário e tenta apanhar-te.                             |")
                    Skip_to.NextDialogue()
                    print("| Ela quase te apanha esticando o seu braço mutante , mas estás salvo. Ela é demasiado grande para caber neste túnel constrangido, adaptado às dimenções        |")
                    print("| de um corpo humano.                                                                                                                                           |")
                    Skip_to.NextDialogue()
                    print("| Criatura - AAAAAGHHHAAAGRRRHNAAAAAAAAAaarRH!!                                                                                                                 |")
                    Skip_to.NextDialogue()
                    print("| A criatura está furiosíssima! Ela retira o braço do túnel e descarga o seu ódio e raiva destruido a mistura de restos humanos e objetos partidos da tua cela. |")
                    Skip_to.NextDialogue()
                    print("| Avanças pelo corredor afora durante o que te parece horas. Eventualmente, vês a luz do dia.                                                                   |")
                    InGameVisuals.ASCII_LVLI_SUCCESS()
                    break
                if opcao == 'B':
                    print("| Decides ficar na tua cela, de pé, estático e em silêncio                                                                                                      |")
                    Skip_to.NextDialogue()
                    print("| - " + (Classes.PlayerCharacter).Nome + " — " + "Esta criatura sobrevive no escuro, ela é provavelmente cega! (*pensamento)                                    " )
                    Skip_to.NextDialogue()
                    print("| - " + (Classes.PlayerCharacter).Nome + " — " + "E impregnei-me do cheiro putrefacto dos restos humanos desta cela, ela não me distinguirá pelo cheiro (*pensamento)")
                    Skip_to.NextDialogue()
                    print("| - Criatura — AAAAAAARRRRRRGHRhr!! HAAAGRRRHNAAAAAAAAAaarRH!!                                                                                                  |")
                    Skip_to.NextDialogue()
                    print("| *Thunk! Whack!                                                                                                                                                |")
                    Skip_to.NextDialogue()
                    print("| A criatura parte a porta da cela e dá-te uma patada no abdomen.                                                                                               |")
                    Skip_to.NextDialogue()
                    print("| És projetado sobre uma pilha de restos humanos, da qual farás parte dentro de segundos.                                                                       |")
                    Skip_to.NextDialogue()
                    print("| - Criatura — AHHRRRaAAAAAGHHHAAAGRR! RHNAAAAAAAAAaarRH!!                                                                                                      |")
                    Skip_to.NextDialogue()
                    print("| Petrificado pela situação, não te consegues mais mecher.                                                                                                      |")
                    Skip_to.NextDialogue()
                    print("| A ultima coisa que vês antes de a criatura devorar a tua cabeça, é a sua cara. Com dezenas de olhos de aranha e mandibulas grotescas.                         |")
                    Skip_to.NextDialogue()
                    print("| A criatura não era cega...|")
                    Skip_to.NextDialogue()
                    InGameVisuals.ASCII_YouDied()
                    break
                if opcao == 'C':                                                                                                                                                              
                    print("| Decides enfrentar a criatura                                                                                                                                  |")
                    Skip_to.NextDialogue()
                    print("| Cruzas olhares com a criatura... Mas não te sentes intimidado                                                                                                 |")
                    Skip_to.NextDialogue()
                    print("| - Criatura — RRRRAAAAAAAAGHHHAAAGRRRHNAAAAAAAAAaarRH!!                                                                                                        |")
                    Skip_to.NextDialogue()
                    print("| Armas-te de coragem e prepáras-te para batalhar com este monstro demoníaco! Avanças-te em direção à criatura                                                  |")
                    Skip_to.NextDialogue()
                    print("| - " + (Classes.PlayerCharacter).Nome + " — " + "AO ATAAAAAAAQUE!!                                                                                             ")
                    Skip_to.NextDialogue()
                    InGameVisuals.ASCII_YouDied()
                    break
                else:
                    print("ERRO: Escolha uma opcao válida.")




        else:
            if opcao != 'A' and opcao != 'B' and opcao != 'C' and opcao != 'D' and opcao != 'X':
                print("ERRO: Escolha uma opcao válida.")
                









# Caso tenhas sido silencioso
                    
def Dilema1_B():
    print("|                                                                                                                                                               |")
    print("| Felizmente os teus movimentos foram silenciosos. Não alertaste a fonte do grito.                                                                              |")
    Skip_to.NextDialogue()
    print("| Isolado no silencio e na escuridão da tua cela, tentas perceber qual é a fonte do grito.                                                                      |")
    Skip_to.NextDialogue()
    UserImputsAndGameOptions.ObservarArredores()
    InGameVisuals.ASCII_OLHO()
    print("|                                                                                                                                                               |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                         | --------------------------------------------~- OBSERVAÇÕES -~------------------------------------------- |                          |")
    print("|                         |                                                                                                          |                          |")
    print("|                         | • Ao sair lentamente da tua cela, olhas para o corredor à tua esquerda. Percebes qual é a fonte do grito.|                          |")
    print("|                         | • Uma criatura mutante vagueia pelos corredores.                                                         |                          |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                         | --------------------------------------------~- OBSERVAÇÕES -~------------------------------------------- |                          |")
    print("|                         |                                                                                                          |                          |")
    print("|                         | • Esfolada e coberta de sangue, esta criatura é uma amalgama grotesta.                                   |                          |")
    print("|                         | • Esfolada e coberta de sangue, é uma amalgama grotesta entre humano, crocodilo, aranha e ratazana.      |                          |")
    print("|                         | • Tem o triplo do teu tamanho. Claramente não és capaz de a derrotar.      |                             |                          |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                                                                                                                                                               |")
    Skip_to.NextDialogue()
    print("- Criatura - gRRRHNAAAARrrg...  AAAgRRRHNAAAAaarRH!!! (Mais gritos)                                                                                             |")
    Skip_to.NextDialogue()
    print("A criatura não te ouviu e parece estar a afastar-se                                                                                                             |")
        
        # fritei aqui, era para continuar a arvore de opcoes mas hoje já não dá :d  




# O DESENROLAR PRINCIPAL DO JOGO

def Jogo():
    clear_terminal()
    print("⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜")
    print("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")
    print("|                                                                      ┏┓┏┳┓┳┏┓  ┏┓┏┓┳┳┓ ┏┓                                                                     |")
    print("| ------------------------------------------------------------------~- ┣  ┃ ┃┃   ┗┓┃┃┃┃┃ ┗┓ -~------------------------------------------------------------------|")
    print("|                                                                      ┗┛ ┻ ┻┗┛  ┗┛┗┛┗┛┗┛┗┛                                                                     |")
    print("|                                                                            NÍVEL I                                                                            |")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")
    print("|                                                                                                                                                               |")

    Skip_to.NextDialogue()
    print("| *Barulho de corpo a ser jogado para o chão                                                                                                                    |")
    Skip_to.NextDialogue()
    print("| *Uma voz sádica ri e desaparece nos ruidos ambientes                                                                                                          |")
    Skip_to.NextDialogue()
    print("| Acordas deitado no chão... Estás só.                                                                                                                          |")
    Skip_to.NextDialogue()
    print("| *Ruidos de gotas a cair do teto e a salpicar no chão.                                                                                                         |")
    Skip_to.NextDialogue()
    print("| Não tens qualquer lembrança. Não sabes quem és, como te chamas nem onde estás...                                                                              |")
    Skip_to.NextDialogue()
    print("| Ao retomar consciencia, tentas perceber o que se passa. Olhas ao teu redor.                                                                                   |")    
    Skip_to.NextDialogue()
    UserImputsAndGameOptions.ObservarArredores()
    InGameVisuals.ASCII_OLHO()
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                         | --------------------------------------------~- OBSERVAÇÕES -~------------------------------------------- |                          |")
    print("|                         |                                                                                                          |                          |")
    print("|                         | • Estás numa pequena sala cúbica, com paredes de pedra. Não há sinal da luz do sol, estás provavelmente  |                          |")
    print("|                         |   debaixo de terra...                                                                                    |                          |")
    print("|                         | • Esta sala é humida e fria, suja, e quase às escuras. Este sítio não te é familiar...                   |                          |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    Skip_to.NextDialogue()
    UserImputsAndGameOptions.ObservarArredores()
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                         | --------------------------------------------~- OBSERVAÇÕES -~------------------------------------------- |                          |")
    print("|                         |                                                                                                          |                          |")
    print("|                         | • Estás deitado numa poça insalubre. Estás encharcado e cheiras a morte...                               |                          |")
    print("|                         | • O teu próprio cheiro quase te faz vomitar.                                                             |                          |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    Skip_to.NextDialogue()
    UserImputsAndGameOptions.ObservarArredores()
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                         | --------------------------------------------~- OBSERVAÇÕES -~------------------------------------------- |                          |")
    print("|                         |                                                                                                          |                          |")
    print("|                         | • Este sítio parece ser numa cela de prisão, num genero de masmorra desmoronada.                         |                          |")
    print("|                         | • Pelos vistos não estás ferido e tens todo o teu equipamento contigo.                                   |                          |")
    print("|                         | • A porta da tua cela está partida e entreaberta. Conseguirias escapar sem dificuldades.                 |                          |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")                                                                  
    Skip_to.NextDialogue()
    UserImputsAndGameOptions.ObservarArredores()
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |")
    print("|                         | --------------------------------------------~- OBSERVAÇÕES -~------------------------------------------- |                          |")
    print("|                         |                                                                                                          |                          |")
    print("|                         | • Uma pequena luz ao fundo do corredor revela uma silhueta humanoide a passar pelos corredores com pés   |                          |")
    print("|                         |   de veludo...                                                                                           |                          |")
    print("|                         ■ —————————————————————————————————————————————————————————————————————————————————————————————————————————■                          |") 
    Skip_to.NextDialogue()
    Dilema1()  


Jogo()

